### ISSUE TITLE
Error in cmake

### ISSUE THREAD

**Issue by abhinavagarwal07** [LARG/utaustinvilla3d#2]
```
-- Could NOT find RCSSNET3D (missing:  RCSSNET3D_INCLUDE_DIR) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
RCSSNET3D_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/user/Desktop/austinnew/utaustinvilla3d

-- Configuring incomplete, errors occurred!
See also "/home/user/Desktop/austinnew/utaustinvilla3d/CMakeFiles/CMakeOutput.log".
See also "/home/user/Desktop/austinnew/utaustinvilla3d/CMakeFiles/CMakeError.log".
```

**Comment by pmacalpine** [comment]
To trouble shoot this issue can you tell me how you installed rcssserver3d (from a package or building and installing it from source)?  Also, as mentioned in the README, did you set the SPARK_DIR environmental variable to the path where you installed the server before running cmake?

**Comment by abhinavagarwal07** [comment]
rcssserver downloaded from 
`https://sourceforge.net/projects/sserver/files/?source=navbar` (v 15.2.2)

installed with `./configure && sudo make && sudo make install`

I have not set `SPARK_DIR` variable and I can use some help in doing so.

Thanks

**Comment by pmacalpine** [comment]
The link you posted for rcssserver is the RoboCup 2D server.  You need the RoboCup 3D server rcssserver3d.  Do you have rcssserver3d installed and if so can you run it?  If you don't have it installed you should be able to get it from the rcssserver3d package.  Instructions for installing rcssserver3d are at http://simspark.sourceforge.net/wiki/index.php/Installation_on_Linux.  Once rcssserver3d is installed, which from the package is probably by default in /usr/, or if you're building and installing from source likely by default in /usr/local/, you can set the SPARK_DIR environmental variable to this location.  For instance, if you're using a bash shell, you would type something like
`export SPARK_DIR=/usr/local`

I believe cmake will look for RCSSNET3D in both /usr/ and /usr/local/ so you probably really only need to set the SPARK_DIR environmental variable if you install the server in a non-default location.  If you install the rcssserver3d package and things still don't work you might also try installing the rcssserver3d-dev package.

**Comment by abhinavagarwal07** [comment]
Thanks installing `rcssserver3d-dev` did the trick.

**Comment by sunfeng90** [comment]
I got this problem too. I installed rcssserver3d by bash shell. I don't know how to install rcssserver3d-dev.

When I type following commands,

`sudo apt-get install rcssserver3d-dev`

I got no software sources.
