### ISSUE TITLE
Bots not moving

### ISSUE THREAD

**Issue by abhinavagarwal07** [LARG/utaustinvilla3d#3]
Even after starting the game, the bots doesn't seem to move

```
user@lenovo:~/Desktop/austinnew/utaustinvilla3d$ ./start.sh 
Running agent No. 1 -- Type 0
UT Austin Villa 3D Simulation Team Base Code
connecting to TCP localhost:3100
Loading rsg: (scene rsg/agent/nao/nao_hetero.rsg 0)
Running agent No. 2 -- Type 0
UT Austin Villa 3D Simulation Team Base Code
connecting to TCP localhost:3100
...
```

![image](https://cloud.githubusercontent.com/assets/8086316/15625204/2a95b90a-24bb-11e6-8ee7-856a96ab297e.png)

**Comment by pmacalpine** [comment]
Currently by default agents just stand in place.  Did you try editing the `selectSkill()` method in `behaviors/strategy.cc` to change this behavior?  There are a number of sample behaviors in `strategy.cc` that you can uncomment and try out.

**Comment by abhinavagarwal07** [comment]
Thanks
