### ISSUE TITLE
make task is failing

### ISSUE THREAD

**Issue by yunicz** [LARG/utaustinvilla3d#5]
Hi, when I try to build this repo I end up with a bunch of error while making.  
cmake task is good
`cmake .
-- The CXX compiler identification is GNU 6.1.1
-- The C compiler identification is GNU 6.1.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   system
-- Found RCSSNET3D: /usr/local/lib/simspark/librcssnet3D.so  
-- No build type selected, default to Release
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yuni/robo/utaustinvilla3d
`

but then i try to make it
`Scanning dependencies of target agentspark
[  2%] Building CXX object CMakeFiles/agentspark.dir/main.cc.o
In file included from /home/yuni/robo/utaustinvilla3d/behaviors/naobehavior.h:10:0,
                 from /home/yuni/robo/utaustinvilla3d/main.cc:11:
/home/yuni/robo/utaustinvilla3d/behaviors/../skills/skill.h:23:13: error: reference to ‘shared_ptr’ is ambiguous
     virtual shared_ptr<Macro> getReflection(BodyModel *bodyModel) = 0;
             ^~~~~~~~~~
In file included from /usr/include/boost/throw_exception.hpp:42:0,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:27,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/local/include/simspark/rcssnet/socket.hpp:29,
                 from /usr/local/include/simspark/rcssnet/tcpsocket.hpp:25,
                 from /home/yuni/robo/utaustinvilla3d/main.cc:6:
/usr/include/boost/exception/exception.hpp:148:11: note: candidates are: template<class T> class boost::shared_ptr
     class shared_ptr;
           ^~~~~~~~~~
In file included from /usr/include/c++/6.1.1/bits/shared_ptr.h:52:0,
                 from /usr/include/c++/6.1.1/memory:82,
                 from /usr/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/local/include/simspark/rcssnet/socket.hpp:29,
                 from /usr/local/include/simspark/rcssnet/tcpsocket.hpp:25,
                 from /home/yuni/robo/utaustinvilla3d/main.cc:6:
/usr/include/c++/6.1.1/bits/shared_ptr_base.h:343:11: note:                 template<class _Tp> class std::shared_ptr
     class shared_ptr;
           ^~~~~~~~~~
In file included from /home/yuni/robo/utaustinvilla3d/behaviors/naobehavior.h:10:0,
                 from /home/yuni/robo/utaustinvilla3d/main.cc:11:
/home/yuni/robo/utaustinvilla3d/behaviors/../skills/skill.h:50:13: error: reference to ‘shared_ptr’ is ambiguous
     virtual shared_ptr<Macro> getReflection(BodyModel *bodyModel);
             ^~~~~~~~~~
In file included from /usr/include/boost/throw_exception.hpp:42:0,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:27,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/local/include/simspark/rcssnet/socket.hpp:29,
                 from /usr/local/include/simspark/rcssnet/tcpsocket.hpp:25,
                 from /home/yuni/robo/utaustinvilla3d/main.cc:6:
/usr/include/boost/exception/exception.hpp:148:11: note: candidates are: template<class T> class boost::shared_ptr
     class shared_ptr;
`

**Comment by mylamour** [comment]
may be you can try change the lower GCC | G++ Version.  I guess.

**Comment by pmacalpine** [comment]
This issue is happening because the GNU CXX 6 compiler enables C++11 (actually C++14) by default resulting in ambiguities between boost:: and std::shared_ptrs.  While it might be a good idea to switch from using boost:: to std::shared_ptrs, I'd prefer not to yet in order to still have compatibility with versions of the GNU CXX compiler that don't fully support C++11.  I can fix the ambiguities in the source without too much trouble, and I might also add the CXX compiler flag -std=gnu++98 (which will also fix the compile errors) to force compilation with the previous GNU CXX compiler default C++ standard and prevent future changes in compiler default standards from breaking things.

**Comment by pmacalpine** [comment]
I decided to just fix the shared_ptr ambiguities and not add the -std=gnu++98 CXX compiler flag so that other standards such as C++11 can still be used if desired.

**Comment by yunicz** [comment]
wow, thank you for that fast reaction. Anyways there are some other compilation errors should I try to fix them and make PR or just mention this in readme that you should use older compiler?

**Comment by pmacalpine** [comment]
I had no problems compiling with the GNU 6.2 compiler on a Ubuntu 14.04 system.  One difference between your setup and mine is that I'm using Boost 1.54 while you're using Boost 1.60.  If you're seeing additional compiler errors please open a new issue for them.
