### ISSUE TITLE
Error in cmake

### ISSUE THREAD

**Issue by sunfeng90** [LARG/utaustinvilla3d#6]
I got following errors.

`-- Could NOT find RCSSNET3D (missing:  RCSSNET3D_INCLUDE_DIR) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.`

I installed rcsserver3d by bash shell. My systems is Ubuntu 18.04.

I set the SPARK_DIR environmental variable.

I don't know how to install rcssserver3d-dev.

When I type following commands,

`sudo apt-get install rcssserver3d-dev`

I got no software sources. Thanks a lot.

**Comment by pmacalpine** [comment]
I'm not sure the rcssserver3d package was ever added to ubuntu 18.04, and so it's best to install it from the command line as you've said you've done.

If you installed rcssserver3d in the default location (`/usr/local`) cmake should automatically find `librcssnet3D.so` at `/usr/local/lib/simspark/librcssnet3D.so`.

Can you run the server?
```
rcssserver3d
```
if not then the server wasn't installed properly and you should try and reinstall it

Where is the server installed?
```
which rcssserver3d
```
Where is `librcssnet3D.so`?
```
locate librcssnet3D.so
```
If the server wasn't installed in the default location then before running cmake you should run the following command based on the following server's install location output from the above commands `<install_dir>/bin/rcssserver3d` and `<install_dir>lib/simspark/librcssnet3D.so` :
```
export SPARK_DIR=<install_dir>
```

**Comment by sunfeng90** [comment]
Firstly, thanks for your reply timely.

Secondly, I can run rcssserver3d.

When I run the following command,

`which rcssserver3d`

I got   `/usr/bin/rcssserver3d`


When I run the following command,

`locate librcssnet3D.so`

I got the following results.

`/usr/lib/simspark/librcssnet3D.so

/usr/lib/simspark/librcssnet3D.so.0

/usr/lib/simspark/librcssnet3D.so.0.1.0
`

Finally, I set the SPARK_DIR by the following command

`export SPARK_DIR=/usr`

But the following error exists all the time.

`-- Could NOT find RCSSNET3D (missing: RCSSNET3D_INCLUDE_DIR) CMake Error: The following variables are used in this project, but they are set to NOTFOUND.`


I'm Chinese. I cannot browse google and cannot install rcssserver3d-dev. I decide to use VPN and install rcssserver3d-dev.
Maybe it will be solved by this way.

Thanks for your reply.

**Comment by sunfeng90** [comment]
Following are all the errors.

frank@frank:~/Project/04robocup3d/Project/UpdatedCode/gzu3d$ cmake .
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
-- Could NOT find RCSSNET3D (missing: RCSSNET3D_INCLUDE_DIR) 
-- No build type selected, default to Release
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
RCSSNET3D_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/frank/Project/04robocup3d/Project/UpdatedCode/gzu3d
   used as include directory in directory /home/frank/Project/04robocup3d/Project/UpdatedCode/gzu3d
   used as include directory in directory /home/frank/Project/04robocup3d/Project/UpdatedCode/gzu3d

-- Configuring incomplete, errors occurred!

**Comment by pmacalpine** [comment]
Hmm I always build and install the server from source rather than from the package.  I suggest building and installing the server from source to see if that works for you https://gitlab.com/robocup-sim/SimSpark/-/wikis/Installation-on-Linux#build-from-source.  Once you install the dependencies and checkout the source code you can just run `build.sh` to build and install everything.

**Comment by sunfeng90** [comment]
Okay. I will try from source. 


Could u share me with /etc/apt/sources.list? I updated it with another version and didn't backup it.


Thanks a lot.


Regards,
Frank 


On 3/29/2022 19:28，Patrick ***@***.***> wrote：

Hmm I always build and install the server from source rather than from the package. I suggest building and installing the server from source to see if that works for you https://gitlab.com/robocup-sim/SimSpark/-/wikis/Installation-on-Linux#build-from-source. Once you install the dependencies and checkout the source code you can just run build.sh to build and install everything.

**Comment by sunfeng90** [comment]
Hi, Should I install latest version of the dependencies?


How about the simspark and rcssserver3d? Should I clone the latest version of them?

Do u have any stable version of them? As far as I can see, There are some bugs in some
latest libs.




Thanks for your reply.


Regards,
Frank


On 3/29/2022 19:28，Patrick ***@***.***> wrote：

Hmm I always build and install the server from source rather than from the package. I suggest building and installing the server from source to see if that works for you https://gitlab.com/robocup-sim/SimSpark/-/wikis/Installation-on-Linux#build-from-source. Once you install the dependencies and checkout the source code you can just run build.sh to build and install everything.

**Comment by sunfeng90** [comment]
I solved all problems from sources. Thanks for your reply, Dr.

**Comment by pmacalpine** [comment]
Closing this issue as the problem has been resolved.
