### ISSUE TITLE
How to train a fast walk

### ISSUE THREAD

**Issue by sunfeng90** [LARG/utaustinvilla3d#7]
Thanks for opening the base code which is helpful for beginners to set up a new team, like me.

I read this code. I found It's too simple for the stable walk.

I want to set up a new team based on this code. How can I train for a fast walk? Which papers I can reference?

I read《Keyframe Sampling, Optimization, and Behavior Integration: Towards Long-Distance Kicking in the RoboCup 3D Simulation League》 which was published by yourself. However, it describes the long-distance not fast walk.

Thanks a lot.

**Comment by pmacalpine** [comment]
The most relevant papers for optimizing a walk are the following:

Patrick MacAlpine, Samuel Barrett, Daniel Urieli, Victor Vu, and Peter Stone.  
Design and Optimization of an Omnidirectional Humanoid Walk: A Winning Approach at the RoboCup 2011 3D Simulation Competition.  
In Proceedings of the Twenty-Sixth AAAI Conference on Artificial Intelligence (AAAI), July 2012.
(http://www.cs.utexas.edu/~pstone/Papers/bib2html/b2hd-AAAI12-MacAlpine.html)
http://www.cs.utexas.edu/~AustinVilla/sim/3dsimulation/AustinVilla3DSimulationFiles/2011/html/walk.html

Patrick MacAlpine and Peter Stone.  
Overlapping Layered Learning.  
Artificial Intelligence (AIJ), 254:21-43, Elsevier, January 2018.
(http://www.cs.utexas.edu/~pstone/Papers/bib2html/b2hd-AIJ18-MacAlpine.html)
http://www.cs.utexas.edu/~AustinVilla/sim/3dsimulation/overlappingLayeredLearning.html

**Comment by sunfeng90** [comment]
Okay, thanks a lot. I will read them.


Regards,
Frank


On 4/8/2022 21:24，Patrick ***@***.***> wrote：

The most relevant papers for optimizing a walk are the following:

Patrick MacAlpine, Samuel Barrett, Daniel Urieli, Victor Vu, and Peter Stone.
Design and Optimization of an Omnidirectional Humanoid Walk: A Winning Approach at the RoboCup 2011 3D Simulation Competition.
In Proceedings of the Twenty-Sixth AAAI Conference on Artificial Intelligence (AAAI), July 2012.
(http://www.cs.utexas.edu/~pstone/Papers/bib2html/b2hd-AAAI12-MacAlpine.html)
http://www.cs.utexas.edu/~AustinVilla/sim/3dsimulation/AustinVilla3DSimulationFiles/2011/html/walk.html

Patrick MacAlpine and Peter Stone.
Overlapping Layered Learning.
Artificial Intelligence (AIJ), 254:21-43, Elsevier, January 2018.
(http://www.cs.utexas.edu/~pstone/Papers/bib2html/b2hd-AIJ18-MacAlpine.html)
http://www.cs.utexas.edu/~AustinVilla/sim/3dsimulation/overlappingLayeredLearning.html
